# Generated by Django 5.0.6 on 2024-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_rename_commment_content_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
